runtime: go120

handlers:
- url: /favicon.png$
  static_files: static/favicon.png
  upload: static/favicon.png

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /images
  static_dir: static/images

- url: /.*
  script: _go_app
  secure: always
  redirect_http_response_code: 301